

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DECar
    {
        public DECar()
        {
            this.DEPermits_History = new HashSet<DEPermits_History>();
        }

        [Display(Name = "ID")]
        public int DECarsID { get; set; }
        [Required]
        public int OwnerId { get; set; }
        [Required]
        [Display(Name = "Make")]
        public int MakeID { get; set; }
        [Required]
        [Display(Name = "Model")]
        public int ModelID { get; set; }
        [Display(Name = "Vehicle")]
        public string CarMakeModel { get; set; }
        public Nullable<int> CarYear { get; set; }
        [Required]
        public string Color { get; set; }
        [Required]
        [Display(Name = "License Plate")]
        public string Plate { get; set; }
        [Required]
        [Display(Name = "State")]
        public string PlateState { get; set; }
        public Nullable<System.DateTime> sys_created_date { get; set; }
        public string sys_created_user { get; set; }
        public bool Terminated { get; set; }
        public Nullable<System.DateTime> TerminatedDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        [Display(Name = "License Number")]
        public string BUSNUM { get; set; }

        public virtual Color Color1 { get; set; }
        public virtual Make Make { get; set; }
        public virtual Model Model { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<DEPermits_History> DEPermits_History { get; set; }
        public virtual DEmployee DEmployee { get; set; }
    }
}
