//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DEmployee
    {
        public DEmployee()
        {
            this.DECars = new HashSet<DECar>();
        }

        [Display(Name = "ID")]
        public int EmplID { get; set; }
        [Required]
        [Display(Name = "Employee Name")]
        public string Name { get; set; }
        [Display(Name = "Address")]
        public string EmplAddress { get; set; }
        [Required]
        [Display(Name = "State")]
        public string EmplState { get; set; }
        [Display(Name = "City")]
        public string EmplCity { get; set; }
        [Display(Name = "Zip Code")]
        public string EmplZipCode { get; set; }
        [Required]
        [Display(Name = "Driver Licence")]
        public string DEP_DL { get; set; }
        [Required]
        [Display(Name = "D.Licence State")]
        public string DEP_DLSTATE { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Phone")]
        public string phone { get; set; }
        public Nullable<System.DateTime> sys_created_date { get; set; }
        public string sys_created_user { get; set; }
        [Display(Name = "Business License #")]
        public string BUSNum { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<DECar> DECars { get; set; }
        public virtual State State { get; set; }
        public virtual State State1 { get; set; }
    }
}
