//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DEPermits_History
    {
        [Display(Name = "ID")]
        public int DEPermits_HistoryID { get; set; }
        [Display(Name = "Permit #")]
        public string DEPermitNumberV { get; set; }
        [Display(Name = "Permit # (int)")]
        public Nullable<int> DEPermitNumberI { get; set; }
        [Display(Name = "EgovID")]
        public Nullable<System.Guid> EgovID { get; set; }
        [Display(Name = "Business License #")]
        public string BUSNum { get; set; }
        public Nullable<int> EmployersContactsID { get; set; }
        [Required]
        public int DECarID { get; set; }
        [Required]
        public int StatusID { get; set; }
        [Display(Name = "Registered")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DEP_APPDATE { get; set; }
        [Display(Name = "Expiration")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DEP_RENEWDATE { get; set; }
        public string Notes { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public Nullable<int> Custom3 { get; set; }
        public bool Terminated { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public System.DateTime sys_created_date { get; set; }
        public string sys_created_user { get; set; }
        [Display(Name = "Employer Name")]
        public string EmployerName { get; set; }
        [Display(Name = "Employer Address")]
        public string EmployerAddress { get; set; }
        [Display(Name = "Employer Email")]
        public string EmployerEmail { get; set; }
        [Display(Name = "Employer Phone")]
        public string EmployerPhone { get; set; }

        public virtual DECar DECar { get; set; }
        public virtual Status Status { get; set; }
    }
}