//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Status
    {
        public Status()
        {
            this.DEPermits_History = new HashSet<DEPermits_History>();
        }
    
        public int ID { get; set; }
        [Display(Name = "Permit Status")]
        public string Status1 { get; set; }
    
        public virtual ICollection<DEPermits_History> DEPermits_History { get; set; }
    }
}
