//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class State
    {
        public State()
        {
            this.DECars = new HashSet<DECar>();
            this.DEmployees = new HashSet<DEmployee>();
            this.DEmployees1 = new HashSet<DEmployee>();
        }
    
        public string Code { get; set; }
        [Display(Name = "State")]
        public string Name { get; set; }
    
        public virtual ICollection<DECar> DECars { get; set; }
        public virtual ICollection<DEmployee> DEmployees { get; set; }
        public virtual ICollection<DEmployee> DEmployees1 { get; set; }
    }
}
