//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DECarsOwnersInfo
    {
        public int DECarsID { get; set; }
        public int EmplID { get; set; }
        public string Name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string DEP_DL { get; set; }
        public string DEP_DLSTATE { get; set; }
        public string CarName { get; set; }
        public int MakeID { get; set; }
        public int ModelID { get; set; }
        public string Plate { get; set; }
        public string PlateState { get; set; }
        public string Color { get; set; }
        public Nullable<int> CarYear { get; set; }
        public string ToDisplay { get; set; }
    }
}
