//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vw_DowntownActiveBusinessLicenses
    {
        public string BLgeeID { get; set; }
        [Display(Name = "Business License #")]
        public string License_Number { get; set; }
        [Display(Name = "License Year")]
        public Nullable<int> License_Year { get; set; }
        public string Classification { get; set; }
        [Display(Name = "License Status")]
        public string License_Status { get; set; }
        public string DBA { get; set; }
        public string Description { get; set; }
        [Display(Name = "Total Employees")]
        public Nullable<double> Employees { get; set; }
        public string DBA_Address_Line1 { get; set; }
        public string DBA_CityStateZip { get; set; }
        public string DBATelePhone { get; set; }
        public string DBAEmail { get; set; }
    }
}
