//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vw_ui_dashboard1
    {
        public string Sorting { get; set; }
        [Display(Name = "Permits Status")]
        public string Permits_Status { get; set; }
        public Nullable<int> Totals { get; set; }
    }
}
