//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPernits
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ui_dashboard2
    {
        public string Sorting { get; set; }
        public string Errors { get; set; }
        public Nullable<int> Value { get; set; }
    }
}
